// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcG9GWTxksZuLOEL42RTFljUxRNaZnB2U',
    appId: '1:776160674781:web:67c2a2b7015c1d262cec34',
    messagingSenderId: '776160674781',
    projectId: 'language-llama',
    authDomain: 'language-llama.firebaseapp.com',
    databaseURL: 'https://language-llama-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'language-llama.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXMCFSGAcOICA3DrbiXmWlamA6FToAE_Q',
    appId: '1:776160674781:android:1caf0ee99bff32eb2cec34',
    messagingSenderId: '776160674781',
    projectId: 'language-llama',
    databaseURL: 'https://language-llama-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'language-llama.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOL0a3TAkdWS_6Bt5oT3jmTEPg1CPSH9c',
    appId: '1:776160674781:ios:12814489233cd30a2cec34',
    messagingSenderId: '776160674781',
    projectId: 'language-llama',
    databaseURL: 'https://language-llama-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'language-llama.appspot.com',
    iosClientId: '776160674781-l4of8j1q445pfc2tne7qc153ag51o7rb.apps.googleusercontent.com',
    iosBundleId: 'com.github.NickPGibson.languagellama',
  );
}
